import { prisma } from "#db/prisma.js";

async function main() {
  await prisma.deliveryArea.createMany({
    data: [
      {
        name: "Lekki Phase 1",
        slug: "lekki-phase-1",
        state: "Lagos State",
        city: "Moba",
        suburb: "Lekki Phase I",
        baseFee: 2500,
        minDeliveryHours: 1,
        maxDeliveryHours: 2,
        latitude: 6.4476101,
        longitude: 3.4693395,
        radiusKm: 5,
        status: "active",
      },
      {
        name: "Victoria Island",
        slug: "victoria-island",
        state: "Lagos State",
        city: "Victoria Island",
        suburb: "Victoria Island",
        baseFee: 2500,
        minDeliveryHours: 1,
        maxDeliveryHours: 2,
        latitude: 6.428055,
        longitude: 3.421944,
        radiusKm: 5,
        status: "active",
      },
      {
        name: "Ikoyi",
        slug: "ikoyi",
        state: "Lagos State",
        city: "Ikoyi",
        suburb: "Maroko",
        baseFee: 3000,
        minDeliveryHours: 1,
        maxDeliveryHours: 2,
        latitude: 6.4467435,
        longitude: 3.4607986,
        radiusKm: 5,
        status: "active",
      },
      {
        name: "Ajah",
        slug: "ajah",
        state: "Lagos State",
        city: "Ajah",
        suburb: "Ajah",
        baseFee: 3500,
        minDeliveryHours: 2,
        maxDeliveryHours: 3,
        latitude: 6.4698,
        longitude: 3.5852,
        radiusKm: 8,
        status: "active",
      },
      {
        name: "Chevron",
        slug: "chevron",
        state: "Lagos State",
        city: "Lekki",
        suburb: "Chevron",
        baseFee: 3000,
        minDeliveryHours: 2,
        maxDeliveryHours: 3,
        latitude: 6.4366,
        longitude: 3.5358,
        radiusKm: 5,
        status: "active",
      },
      {
        name: "Ikeja",
        slug: "ikeja",
        state: "Lagos State",
        city: "Ikeja",
        suburb: "Computer Village",
        baseFee: 4000,
        minDeliveryHours: 2,
        maxDeliveryHours: 4,
        latitude: 6.6018,
        longitude: 3.3515,
        radiusKm: 8,
        status: "active",
      },
      {
        name: "Yaba",
        slug: "yaba",
        state: "Lagos State",
        city: "Yaba",
        suburb: "Sabo",
        baseFee: 3500,
        minDeliveryHours: 2,
        maxDeliveryHours: 3,
        latitude: 6.5095,
        longitude: 3.3711,
        radiusKm: 6,
        status: "active",
      },
      {
        name: "Surulere",
        slug: "surulere",
        state: "Lagos State",
        city: "Surulere",
        suburb: "Aguda",
        baseFee: 3500,
        minDeliveryHours: 2,
        maxDeliveryHours: 4,
        latitude: 6.4969,
        longitude: 3.3537,
        radiusKm: 7,
        status: "active",
      }
    ],
    skipDuplicates: true,
  });

  console.log("Delivery areas seeded.");
}

main()
  .finally(() => prisma.$disconnect());